name: Push Build

on:
  push:
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: |
        cd translate
        pip install -r requirements.txt
        ./gen_rc.sh
      shell: bash
    - run: |
        mkdir .nuget
        cd .nuget
        curl -OL https://github.com/ysc3839/GitInfo/releases/download/v2.0.33/GitInfo.2.0.33.nupkg
        nuget sources add -name gitinfo -source `cygpath -wa .`
        cd ..
        nuget restore ClashXW.sln
      shell: bash
    - run: |
        vcpkg install skyr-url --triplet=arm64-windows-static
        vcpkg install skyr-url --triplet=x64-windows-static
        vcpkg install skyr-url --triplet=x86-windows-static
        vcpkg integrate install
      shell: cmd
    - run: |
        Start-Job -Init ([ScriptBlock]::Create("Set-Location '$pwd'")) -Script {
          msbuild ClashXW.sln "-p:Configuration=Release;Platform=x64" }
        Start-Job -Init ([ScriptBlock]::Create("Set-Location '$pwd'")) -Script {
          msbuild ClashXW.sln "-p:Configuration=Release;Platform=x86" }
        Start-Job -Init ([ScriptBlock]::Create("Set-Location '$pwd'")) -Script {
          msbuild ClashXW.sln "-p:Configuration=Release;Platform=ARM64" }
        Get-Job | Wait-Job | Receive-Job
      shell: powershell
    - uses: actions/upload-artifact@v2
      with:
        name: ClashXW64.exe
        path: x64/Release/ClashXW64.exe
    - uses: actions/upload-artifact@v2
      with:
        name: ClashXW64.pdb
        path: x64/Release/ClashXW64.pdb
    - uses: actions/upload-artifact@v2
      with:
        name: ClashXW32.exe
        path: Release/ClashXW32.exe
    - uses: actions/upload-artifact@v2
      with:
        name: ClashXW32.pdb
        path: Release/ClashXW32.pdb
    - uses: actions/upload-artifact@v2
      with:
        name: ClashXWARM64.exe
        path: ARM64/Release/ClashXWARM64.exe
    - uses: actions/upload-artifact@v2
      with:
        name: ClashXWARM64.pdb
        path: ARM64/Release/ClashXWARM64.pdb
